apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meta-cluster2-infra
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ably77/aoa-cluster2/
    targetRevision: HEAD
    path: environment/infra/active/
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: false